apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medimetrics

resources:
  - namespace.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - inference-deployment.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - ingress.yaml

configMapGenerator:
  - name: medimetrics-config
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - ENABLE_METRICS=true

secretGenerator:
  - name: medimetrics-secrets
    literals:
      - database-url=postgres://postgres:postgres@postgres:5432/medimetrics
      - redis-url=redis://:redis123@redis:6379/0
      - jwt-secret=change-me-in-production
      - encryption-key=change-me-in-production

commonLabels:
  app.kubernetes.io/name: medimetrics
  app.kubernetes.io/instance: production
  app.kubernetes.io/component: medical-imaging
  app.kubernetes.io/part-of: medimetrics-enterprise