services:
  # API Service - Isolated build
  - type: web
    name: medimetrics-api
    env: node
    rootDir: medimetrics-enterprise/apps/api
    buildCommand: |
      npm cache clean --force
      npm install --legacy-peer-deps || npm install --force
    startCommand: node src/main.js || npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medimetrics-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8000

  # Web Frontend - Isolated build
  - type: web
    name: medimetrics-frontend
    env: node
    rootDir: medimetrics-enterprise/apps/web
    buildCommand: |
      npm cache clean --force
      npm install --legacy-peer-deps || npm install --force
      npm run build
    startCommand: npx next start -p $PORT || npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://medimetrics-api.onrender.com

databases:
  - name: medimetrics-db
    databaseName: medimetrics