services:
  # API Service - Minimal setup
  - type: web
    name: medimetrics-api
    env: node
    buildCommand: |
      cd medimetrics-enterprise/apps/api
      npm install
    startCommand: |
      cd medimetrics-enterprise/apps/api
      npm start || node src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medimetrics-db
          property: connectionString

  # Frontend - Minimal Next.js
  - type: web
    name: medimetrics-frontend
    env: node  
    buildCommand: |
      cd medimetrics-enterprise/apps/web
      npm install || echo "Install done"
      npm run build || echo "Build done"
    startCommand: |
      cd medimetrics-enterprise/apps/web
      npm run start || node server.js || npx next start -p $PORT
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: medimetrics-db
    databaseName: medimetrics