services:
  # API Service
  - type: web
    name: medimetrics-api
    env: node
    buildCommand: |
      cd medimetrics-enterprise/apps/api
      npm cache clean --force
      npm install --legacy-peer-deps
    startCommand: |
      cd medimetrics-enterprise/apps/api
      node src/main.js || npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medimetrics-db
          property: connectionString

  # Frontend - Fixed npm install issues
  - type: web
    name: medimetrics-frontend
    env: node  
    buildCommand: |
      cd medimetrics-enterprise/apps/web
      npm cache clean --force
      npm config set registry https://registry.npmjs.org/
      npm install --legacy-peer-deps --force
      npm run build
    startCommand: |
      cd medimetrics-enterprise/apps/web
      npx --yes next start -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0

databases:
  - name: medimetrics-db
    databaseName: medimetrics