services:
  # API Service (keep as-is)
  - type: web
    name: medimetrics-api
    env: node
    rootDir: medimetrics-enterprise/apps/api
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medimetrics-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  # Keep the static site but don't try to change it
  - type: static
    name: medimetrics-web
    staticPublishPath: ./medimetrics-enterprise
    buildCommand: echo "Keeping as placeholder"

  # Add a new web service for the actual Next.js app
  - type: web
    name: medimetrics-frontend
    env: node
    rootDir: medimetrics-enterprise/apps/web
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://medimetrics-api.onrender.com

databases:
  - name: medimetrics-db
    databaseName: medimetrics