services:
  # NestJS API Service
  - type: web
    name: medimetrics-api
    env: node
    buildCommand: |
      cd medimetrics-enterprise/apps/api
      npm install --include=dev
      npx nest build || npm run build
    startCommand: |
      cd medimetrics-enterprise/apps/api
      npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medimetrics-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: PORT
        value: 8000

  # Next.js Frontend
  - type: web
    name: medimetrics-frontend
    env: node
    buildCommand: |
      cd medimetrics-enterprise/apps/web
      npm install
      npm run build
    startCommand: |
      cd medimetrics-enterprise/apps/web
      npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://medimetrics-api.onrender.com

databases:
  - name: medimetrics-db
    databaseName: medimetrics