services:
  # Main Web Application
  - type: web
    name: medimetrics-web
    env: static
    staticPublishPath: ./medimetrics-enterprise
    buildCommand: echo "Static site ready"
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /api/*
        destination: https://medimetrics-api.onrender.com/api/*

  # API Service
  - type: web
    name: medimetrics-api
    env: node
    buildCommand: cd medimetrics-enterprise/apps/api && npm install
    startCommand: cd medimetrics-enterprise/apps/api && node src/main.js || npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: medimetrics-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: medimetrics-db
    databaseName: medimetrics