{{- if .Values.agent.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "energy.agent.fullname" . }}
  labels:
    {{- include "energy.agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "energy.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "energy.agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "energy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imageRegistry }}/{{ .Values.agent.image.repository }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PORT
              value: "9100"
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: dev
              mountPath: /dev
              readOnly: true
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: dev
          hostPath:
            path: /dev
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
{{- end }}
