version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: power_platform_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-powerdb}
      POSTGRES_USER: ${DATABASE_USER:-poweruser}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-powerpass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poweruser"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: power_platform_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ../backend
      dockerfile: ../deploy/Dockerfile.backend
    container_name: power_platform_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../backend:/app
      - shared_storage:/app/static/exports
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://poweruser:powerpass@postgres:5432/powerdb
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - STORAGE_PATH=/app/static/exports
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-true}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build:
      context: ../backend
      dockerfile: ../deploy/Dockerfile.backend
    container_name: power_platform_worker
    command: celery -A app.workers.celery_app worker --loglevel=info
    volumes:
      - ../backend:/app
      - shared_storage:/app/static/exports
    environment:
      - DATABASE_URL=postgresql://poweruser:powerpass@postgres:5432/powerdb
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - STORAGE_PATH=/app/static/exports
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ../frontend
      dockerfile: ../deploy/Dockerfile.frontend
    container_name: power_platform_frontend
    command: npm run dev
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    container_name: power_platform_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - shared_storage:/usr/share/nginx/html/static
    depends_on:
      - api
      - frontend

volumes:
  postgres_data:
  shared_storage:

networks:
  default:
    name: power_platform_network
