# Energy Orchestrator v0.7.0 - Complete Configuration
namespace: energy-system
imageRegistry: ghcr.io/yourorg/energy-orchestrator
imageTag: v0.7.0
imagePullPolicy: IfNotPresent

# Core Components
agent:
  enabled: true
  daemonset: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

energyApi:
  enabled: true
  replicas: 2
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

controller:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

notifier:
  enabled: true
  interval: 3600
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Advanced Features
greenWindow:
  enabled: true
  windows: "00:00-06:00,22:00-24:00"  # UTC
  targetNamespaces:
    - default
    - batch-jobs
  powerRelaxPercent: 5
  batchBump: 1

trtllmTuner:
  enabled: true
  targetNamespace: default
  appLabel: trtllm-demo
  targetP95Seconds: 0.2
  batchMin: 1
  batchMax: 8
  powerCapMin: 120
  powerCapMax: 300

# Monitoring
monitoring:
  enabled: true
  grafana:
    enabled: true
    adminPassword: admin-energy-2024
  prometheus:
    retention: 30d
    storageSize: 50Gi

# Grafana Features
grafana:
  apiUrl: ""  # Auto-detected if empty
  apiToken: ""  # Set your Grafana API token
  dashboards:
    uids:
      - energy-efficiency
      - app-energy
  snapshot:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    expiresSeconds: 86400
    webhookUrl: ""  # Optional webhook for snapshot URLs

# Report Generation
report:
  enabled: false  # Enable when ready to generate report
  promUrl: ""  # Auto-detected if empty
  start: "2025-01-01T00:00:00Z"
  mid: "2025-01-15T00:00:00Z"
  end: "2025-01-30T00:00:00Z"

# KEDA
keda:
  enabled: true

# Alerts
alerts:
  enabled: true
  targetJoulesPerReq: 200
  slack:
    enabled: true
    webhookUrl: ""
    channel: "#energy-alerts"
  webhook:
    enabled: false
    url: ""

# Optimization Parameters
optimization:
  pidGains:
    kp: 2.0
    ki: 0.2
    kd: 0.0
  batchLimits:
    min: 1
    max: 8
  powerLimits:
    gpuFloor: 120
    gpuCeiling: 300
    cpuFloor: 50
    cpuCeiling: 150

# Default Policies
defaultPolicies:
  inference:
    p95LatencyMs: 200
    errorRatePercent: 0.1
    targetJoulesPerRequest: 150
  training:
    p95LatencyMs: 5000
    errorRatePercent: 1.0
    targetJoulesPerRequest: 500
  batch:
    p95LatencyMs: 30000
    errorRatePercent: 2.0
    targetJoulesPerRequest: 1000