apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medimetrics

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - minio-deployment.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - inference-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: medimetrics
  app.kubernetes.io/part-of: medimetrics-platform